modLoader="javafml"
loaderVersion="[47,)"
license="All Rights Reserved"

[[mods]]
modId="ducksgalore"
version="${file.jarVersion}"
displayName="Ducks Galore"
# logoFile="examplemod.png" 
credits="Thanks to the Forge team and the Minecraft modding community"
authors="Hutizaki"
description='''
A mod that adds various rubber ducks to Minecraft.
Golden rubber ducks provide special powers when you need them most!
'''

[[dependencies.ducksgalore]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.ducksgalore]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,1.21)"
    ordering="NONE"
    side="BOTH"

[[dependencies.ducksgalore]]
    modId="create"
    mandatory=false
    versionRange="[0.5.1,)"
    ordering="AFTER"
    side="BOTH" 